geters netsample
yandex/pandora pull request #196
Opened 2024-09-04 09:49 UTC by seferen

Add geters to netsamle

2024-09-04 11:20 UTC, nickclmb requested changes

2024-09-04 11:20 UTC, nickclmb commented on core/aggregator/netsample/sample.go
> +func (s *Sample) GetUserDuration() int {
The `Time` and `Duration` getter names should be `Get...Milliseconds` because the getter returns a different type than the setter.

2024-09-05 12:22 UTC, seferen commented
function was renamed

2024-09-05 12:53 UTC, merged

2024-09-05 12:54 UTC, nickclmb commented
PR was merged, thanks for your contribution!